### ISSUE TITLE
{% extends %} doesn't use quotes

### ISSUE THREAD

**Issue by SmileyChris** [funkybob/knights-templater#16]
It'd be more consistent from a user's perspective if the template name had to be a string.

On a related note, does it *have* to be loaded on parse? Not having it hard coded would make for more flexibility...

**Comment by funkybob** [comment]
I can switch the parsing to work more like include does currently.

As to on-parse, since it's sub-classing the template class it "extends", I'm having trouble thinking of a non-footgun approach to late binding inheritance.

**Comment by funkybob** [comment]
quotes are now required.

Please open a separate ticket to discuss late inheritance.
